-- =========================================
-- USERS
-- =========================================

create table if not exists public.users (
    uid uuid primary key default gen_random_uuid(),

    email text not null unique,

    password_hash text not null,

    created_at timestamptz not null default now()
);


-- =========================================
-- CHAT HISTORY
-- =========================================

create table if not exists public.chat_history (
    id bigint generated by default as identity primary key,

    uid uuid not null
        references public.users(uid)
        on delete cascade,

    session_id uuid not null,

    role text not null
        check (role in ('user', 'assistant')),

    message text not null,

    created_at timestamptz not null default now()
);


-- =========================================
-- INDEX
-- =========================================

create index if not exists chat_history_uid_session_created_idx
on public.chat_history(uid, session_id, created_at);


-- =========================================
-- ENABLE RLS
-- =========================================

alter table public.users enable row level security;
alter table public.chat_history enable row level security;